# general settings for Dehazing training
name: train_MaIR_R6K
model_type: ImageCleanModel
scale: 1
num_gpu: 4  # set num_gpu: 0 for cpu mode
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: RESIDE-6K
    type: Dataset_PairedImage
    dataroot_gt: /xlearning/boyun/datasets/reside-mix/train/gt/
    dataroot_lq: /xlearning/boyun/datasets/reside-mix/train/hazy/
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 32
    batch_size_per_gpu: 6

    mini_batch_sizes: [6, 2]             # Batch size per gpu   
    iters: [250000, 150000]
    gt_size: 256   # Max patch size for progressive training
    gt_sizes: [256, 384]  # Patch sizes for progressive training.

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: RESIDE-Mix
    type: Dataset_PairedImage
    dataroot_gt:  /data/boyun/datasets/reside-mix/test/gt
    dataroot_lq:  /data/boyun/datasets/reside-mix/test/hazy
    io_backend:
      type: disk

# network structures
network_g:
  type: MaIRUNet
  inp_channels: 3
  out_channels: 3
  dim: 24
  num_blocks: [2, 2, 3, 4]
  num_refinement_blocks: 2

  ssm_ratio: 1.2 
  flp_ratio: 2.0 
  mlp_ratio: 2.0 
  bias: False
  dual_pixel_task: False

  img_size: 256
  scan_len: 8
  batch_size: 6
  dynamic_ids: False


# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 400000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [100000, 300000]
    restart_weights: [1,1]
    eta_mins: [0.0002,0.000001]   
  
  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 800e3
  val_freq_final: !!float 5e3
  val_milestone: 300000 

  window_size: 8
  # val_freq: !!float 4e3
  save_img: false
  rgb2bgr: false
  use_image: false
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false


# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 10e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
